config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  root 'home#index'
  get 'contacts' => 'contacts#index'

  namespace :admin do
    root 'slides#index'
    resources :slides
    resources :pages
  end

  get ':page_name' => 'pages#show'
end

app/models/ckeditor/asset.rb
# == Schema Information
#
# Table name: ckeditor_assets
#
#  id                :integer          not null, primary key
#  data_file_name    :string(255)      not null
#  data_content_type :string(255)
#  data_file_size    :integer
#  assetable_id      :integer
#  assetable_type    :string(30)
#  type              :string(30)
#  width             :integer
#  height            :integer
#  created_at        :datetime
#  updated_at        :datetime
#

class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
# == Schema Information
#
# Table name: ckeditor_assets
#
#  id                :integer          not null, primary key
#  data_file_name    :string(255)      not null
#  data_content_type :string(255)
#  data_file_size    :integer
#  assetable_id      :integer
#  assetable_type    :string(30)
#  type              :string(30)
#  width             :integer
#  height            :integer
#  created_at        :datetime
#  updated_at        :datetime
#

class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    :url => "/ckeditor_assets/attachments/:id/:filename",
                    :path => ":rails_root/public/ckeditor_assets/attachments/:id/:filename"

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 100.megabytes
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
# == Schema Information
#
# Table name: ckeditor_assets
#
#  id                :integer          not null, primary key
#  data_file_name    :string(255)      not null
#  data_content_type :string(255)
#  data_file_size    :integer
#  assetable_id      :integer
#  assetable_type    :string(30)
#  type              :string(30)
#  width             :integer
#  height            :integer
#  created_at        :datetime
#  updated_at        :datetime
#

class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    :url  => "/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :path => ":rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :styles => { :content => '800>', :thumb => '118x100#' }

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 2.megabytes
  validates_attachment_content_type :data, :content_type => /\Aimage/

  def url_content
    url(:content)
  end
end

app/models/page.rb
# == Schema Information
#
# Table name: pages
#
#  id                 :integer          not null, primary key
#  name               :string(255)
#  title              :string(255)
#  image_file_name    :string(255)
#  image_content_type :string(255)
#  image_file_size    :integer
#  image_updated_at   :datetime
#  file_file_name     :string(255)
#  file_content_type  :string(255)
#  file_file_size     :integer
#  file_updated_at    :datetime
#  text_block_1       :text
#  text_block_2       :text
#  created_at         :datetime
#  updated_at         :datetime
#

class Page < ActiveRecord::Base
  has_attached_file :image, styles: {admin_thumb: '128x128'}
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  has_attached_file :file
  do_not_validate_attachment_file_type :file
end

app/models/slide.rb
# == Schema Information
#
# Table name: slides
#
#  id                 :integer          not null, primary key
#  image_file_name    :string(255)
#  image_content_type :string(255)
#  image_file_size    :integer
#  image_updated_at   :datetime
#  title              :string(255)
#  text               :text
#  created_at         :datetime
#  updated_at         :datetime
#

class Slide < ActiveRecord::Base
  has_attached_file :image, styles: {admin_thumb: '128x128', slide: '1051x616#'}
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/controllers/admin/pages_controller.rb
class Admin::PagesController < AdminController
  before_action :find_page, only: [:edit, :update, :destroy]
  def index
    @pages = Page.all
  end

  def edit
  end

  def update
    if @page.update(page_params)
      redirect_to admin_pages_path
    else
      render 'edit'
    end
  end

  def destroy
    @page.destroy
    redirect_to admin_pages_path
  end

  private
    def find_page
      @page = Page.find params[:id]
    end

    def page_params
      params.require(:page).permit(:image, :title, :file, :text_block_1, :text_block_2)
    end
end

app/controllers/admin/slides_controller.rb
class Admin::SlidesController < AdminController
  before_action :find_slide, only: [:edit, :update, :destroy]
  def index
    @slides = Slide.all
  end

  def new
    @slide = Slide.new
  end

  def create
    @slide = Slide.new(slide_params)
    if Slide.all.count <=2 && @slide.save
      redirect_to admin_slides_path
    else
      render 'edit'
    end
  end

  def edit
  end

  def update
    if @slide.update(slide_params)
      redirect_to admin_slides_path
    else
      render 'edit'
    end
  end

  def destroy
    @slide.destroy
    redirect_to admin_slides_path
  end

  private
    def find_slide
      @slide = Slide.find params[:id]
    end
    def slide_params
      params.require(:slide).permit(:image, :title, :text)
    end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  http_basic_authenticate_with name: "admin", password: "123"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @slides = Slide.take 3
  end
end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
  def index
  end

  def gofrocarton
    @page = Page.find_by(name: 'gofrocarton')
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
    @page = Page.find_by name: params[:page_name]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def nav_active path
    (request.path == path) ? "active" : nil
  end
end

app/views/admin/pages/_form.html.slim
= form_for [:admin, @page], html:{class: 'form-horizontal'} do |f|
  / .form-group
  /   = f.label 'Заголовок', class: "col-sm-1 control-label"
  /   .col-sm-6
  /     = f.text_field :title, required:'', class:"form-control"
  .form-group
    = f.label 'Левый блок', class: "col-sm-1 control-label"
    .col-sm-10
      = f.cktext_area :text_block_1, class:"form-control"
  .form-group
    = f.label 'Правый блок', class: "col-sm-1 control-label"
    .col-sm-10
      = f.cktext_area :text_block_2, class:"form-control"
  - if f.object.image?
    .form-group
      = f.label 'Текущее изображение', class: "col-sm-1 control-label"
      .col-sm-10
        = image_tag f.object.image.url :admin_thumb
  .form-group
    = f.label 'Изображение', class: "col-sm-1 control-label"
    .col-sm-10
      = f.file_field :image, class: "form-control"
  .form-group
    = f.label 'Файл', class: "col-sm-1 control-label"
    .col-sm-10
      = f.file_field :file, class: "form-control"
  .form-group
    .col-sm-offset-1.col-sm-10
      = f.submit 'Сохранить', class: "btn btn-primary form-control"

app/views/admin/pages/edit.html.slim
h2 Редактирование страницы
= render 'form'

app/views/admin/pages/index.html.slim
h2 Страницы
table.table
  thead
    th ID
    th Изображение
    th Заголовок
    th Действия
  - @pages.each do |page|
    tr
      td = page.id
      td = image_tag page.image.url(:admin_thumb)
      td = page.title
      td = link_to "Редактировать", edit_admin_page_path(page)

app/views/admin/slides/_form.html.slim
= form_for [:admin, @slide], html:{class: 'form-horizontal'} do |f|
  .form-group
    = f.label 'Заголовок', class: "col-sm-1 control-label"
    .col-sm-6
      = f.text_field :title, required:'', class:"form-control"
  .form-group
    = f.label 'Текст', class: "col-sm-1 control-label"
    .col-sm-6
      = f.text_area :text, required:'', class:"form-control"
  - if f.object.image?
    .form-group
      = f.label 'Текущее изображение', class: "col-sm-1 control-label"
      .col-sm-6
        = image_tag f.object.image.url :admin_thumb
  .form-group
    = f.label 'Изображение', class: "col-sm-1 control-label"
    .col-sm-6
      = f.file_field :image, class: "form-control"
  .form-group
    .col-sm-offset-1.col-sm-6
      = f.submit 'Сохранить', class: "btn btn-primary form-control"

app/views/admin/slides/edit.html.slim
h2 Редактирование слайда
= render 'form'

app/views/admin/slides/index.html.slim
h2 Слайды
table.table
  thead
    th Изображение
    th Заголовок
    th Дополнительный текст
    th.text-center colspan="2" Действия
  - @slides.each do |slide|
    tr
      td = image_tag slide.image.url :admin_thumb
      td = slide.title
      td = slide.text
      td = link_to "Редактировать", edit_admin_slide_path(slide)
      td
        a= link_to "Удалить", [:admin, slide], method: :delete, data: { confirm: "Подтверждаете удаление?" }
br
- unless Slide.all.count >= 3
  = link_to 'Добавить слайд', new_admin_slide_path, class: "btn btn-primary"

app/views/admin/slides/new.html.slim
h2 Создание слайда
= render 'form'

app/views/contacts/index.slim
- content_for(:body_id, :contacts)

script src="http://maps.googleapis.com/maps/api/js?sensor=FALSE"

javascript:
  function initialize() {
    var mapOptions = {
      center: new google.maps.LatLng(58.39,33.902769),
      zoom: 14,
      disableDefaultUI: true,
      mapTypeId: google.maps.MapTypeId.ROADMAP
    };
    var map = new google.maps.Map(document.getElementById("map"), mapOptions);
    myLatlng = new google.maps.LatLng(58.385340,33.844582);
    $('#information li').eq(0).click( function() {
      map.setOptions({center: myLatlng, zoom: 15});
    });
    $('#information li').eq(1).click( function() {
      map.setOptions({center: myLatlng, zoom: 15});
    });
    var marker = new google.maps.Marker({
      position: myLatlng,
      map: map
    });
    myLatlng2 = new google.maps.LatLng(58.658253,34.315600);
    $('#information li').eq(2).click( function() {
      map.setOptions({center: myLatlng2, zoom: 15});
    });
    var marker2 = new google.maps.Marker({
      position: myLatlng2,
      map: map
    });
  }
  $(document).ready(function() {
    initialize();
  });

ul#information
  li
    .num 1
    b Офис:
    p
      | 174437, поселок Удино, ул. Центральная д.1,
      br
      |  Боровичский р-н., Новгородская область
      br
      | +7 (81664) 9-45-10, +7 (81664) 9-45-18
      br
      | +7 (81664) 9-45-49
      br
      | info@bkbf.su
  li
    .num 2
    b Производство бумаги и картона
    p новгородская область, г.боровичи, ул.окуловская;
  li
    .num 3
    b Производство гофрокартона и упаковки:
    p
      | 174437, поселок Удино, ул. Центральная д.1,
      br
      |  Боровичский р-н., Новгородская область

app/views/home/index.slim
- content_for(:body_id, :home)

.section
  .line
    - @slides.each do |slide|
      .slide
        =image_tag slide.image.url(:slide)
        h2=slide.title
        .message= simple_format slide.text
.buttons
  input.but.active type='button' value='1'
  input.but type='button' value='2'
  input.but type='button' value='3'

app/views/layouts/_breadcrumbs.slim
#breadcrumbs
  = link_to '/'
    ' БКБФ
  ' /
  =link_to @page.title, "/#{@page.name}"

app/views/layouts/_footer.slim
#copyright
  strong
    ' 1994-2014
  | боровичская картоннобумажная фабрика
  br
  | ЗАО МЕТАЛЛОПЛАСТМАСС
#cj-logo
  =link_to 'http://crimsonjackets.ru/', :target => "_blank"
    =image_tag 'web_cj.png'

app/views/layouts/_header.slim
nav
  ul
    li.logo-li
      = link_to '/'
        = image_tag 'web_bkbf_menu.png'
        .logo
          | боровичская
          br
          | картонно-бумажная
          br
          | фабрика
          br
          span ЗАО&nbsp;&nbsp;&nbsp;&nbsp;МЕТАЛЛОПЛАСТМАСС
    li class="#{'active' if (yield(:body_id) == "company")}"
      =link_to '/company'
        .num 1
        .name компания
    li class="#{'active' if (yield(:body_id) == "gofrocarton")}"
      =link_to '/gofrocarton'
        .num 2
        .name гофрокартон
    li class="#{'active' if (yield(:body_id) == "gofropack")}"
      =link_to '/gofropack'
        .num 3
        .name гофроупаковка
    li class="#{'active' if (yield(:body_id) == "carton_paper")}"
      =link_to '/carton_paper'
        .num 4
        .name бумага и картон
    li class="#{'active' if (yield(:body_id) == "contacts")}"
      =link_to '/contacts'
        .num 5
        .name контакты
    li
      .contacts
        | 174437, поселок Удино, ул. Центральная д.1,
        br
        | Боровичский р-н., Новгородская область
      .tel
        / | (812) 947 21 40
        / br
        | т. +7 (81664) 945-10, ф. +7 (81664) 945-49
        br
        | info@bkbf.su

app/views/layouts/admin.html.slim
doctype html
html
  head
    title Панель администратора
    = stylesheet_link_tag    "admin", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "admin", "data-turbolinks-track" => true
    = csrf_meta_tags
  body
    nav.navbar.navbar-default role="navigation" 
      .container-fluid
        .navbar-header
          button.navbar-toggle data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button" 
            span.sr-only Toggle navigation
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.navbar-brand href="/" BKBF
        #bs-example-navbar-collapse-1.collapse.navbar-collapse
          ul.nav.navbar-nav
            li class=nav_active('/admin/slides')
              a href="/admin/slides" Слайдер
            li class=nav_active('/admin/pages')
              a href="/admin/pages" Страницы
            

    .container
      = yield

app/views/layouts/application.slim
doctype html
html
  head
    title Bkbf
    meta charset='utf-8'
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  body id="#{yield :body_id}"
    #map
    header#header = render 'layouts/header'
    #content = yield
    footer#footer = render 'layouts/footer'

app/views/materials/gofrocarton.slim
- content_for(:body_id, :carton)

= render 'layouts/breadcrumbs'
.left-column
  .full-block.main-img
    =image_tag @page.image.url
    h1.img-name Гофрокартон.
  .full-block
    .block-name Гофрокартон. общая информация.
    .base == @page.text_block_1
.right-column
  .small-block.first
    h2 Цены и характеристики гофрокартона.
    = link_to 'Скачать', @page.file.url, class: 'download'
  .small-block.first.last
    h2.sm
      | БКБФ - современные технологии и&nbsp;проверенные механизмы.
    ul.best
      li Своя лаборатория.
      li Сертификация.
      li Специалисты высшей категории.
  .full-block
    .block-name гофрокартон бкбф
    .base == @page.text_block_2

app/views/pages/show.html.slim
- content_for(:body_id, @page.name.to_sym)

= render 'layouts/breadcrumbs'


.left-column
  .full-block.main-img
    =image_tag @page.image.url
    h1.img-name= @page.title
  .full-block
    .block-name
      - if @page.name != 'company'
        | #{@page.title}
      - else
        | История компании
    .base == @page.text_block_1
.right-column
  - if @page.name != 'company'
    .small-block.first
      h2 БКБФ Сегодня
      = link_to 'Скачать', @page.file.url, class: 'download'
    .small-block.first.last
      h2.sm
        | БКБФ - современные технологии и&nbsp;проверенные механизмы.
      ul.best
        li Своя лаборатория.
        li Сертификация.
        li Специалисты высшей категории.
  - else
    .full-block style="height: 280px"
      .base
        p
          strong
            span style="font-size:22px" БКБФ сегодня.

        p Мы являемся единственным предприятием в России перерабатывающим многослойный пищевой картон, что благоприятно сказывается на экологии страны.
        / p
          / span style="font-size:16px" На данный момент, мы являемся единственным предприятием в России, которое &nbsp;перерабатывает многослойный пищевой картон, что благоприятно сказывается на экологии и развивает рынок вторсырья в нашей стране.
        table border="0" cellpadding="0" cellspacing="0" class="count-table" style=""
          tbody
            tr
              td
                div class="in-count" 105
              td
                div class="in-count" 2
              td
                div class="in-count" 3
            tr
              td
                p
                  span style="font-size:12px" Лет опыта в бумажной отрасли
              td
                p
                  span style="font-size:12px" Высокотехнологичных производства
              td
                p
                  span style="font-size:12px" Гектара леса в сутки сохраняется&nbsp;
                  span style="font-size:12px" благодаря нашему предприятию
  .full-block
    .block-name
      - if @page.name != 'company'
        | #{@page.title}
      - else
        | Описание
    .base == @page.text_block_2